# global 
random_seed: 0
use_cache: False

# agent 
agent:
  problem:
    path: datasets/fveval_nl2sva_machine.jsonl
    num_samples: TODO
    batch_size: -1
    models:
      - sva : &action_model TODO

  generation:
    path: TODO
    max_workers: 32
    batch_size: 1 
    timeout: 2000000

    sva:
      use_header_as_prefix: True
      use_detailed_prompt: False
      query:
        model: *action_model
        tokenizer_path: *action_model
        temperature: 0.8
        top_p: 0.95
        max_tokens: TODO
        # stop: []
        use_system_prompt: True
        use_chat: True
        system_prompt: "You are an AI assistant tasked with formal verification of register transfer level (RTL) designs.\nYour job is to translate a description of an assertion to concrete SystemVerilog Assertion (SVA) implementation.\n"
        timeout: 2000000
  
  verification:
    path: TODO
    max_workers: 32
    batch_size: 1
    timeout: 600


# Verifier
verifier:
  host: 127.0.0.1
  port: 4422
  max_workers: 128
  queue_max_size: 1024
  memory_limit: 10
  time_limit: 180

# vllm server
llm_kit:
  server_type: vllm 
  host: 127.0.0.1
  router_port: 2244
  router_timeout: 1000000
  api_key: token-vllm-server

  models:
    - model: *action_model
      tensor_parallel_size: 4
      pipeline_parallel_size: 1
      data_parallel_size: 2
      random_seeds:
        - 42
        - 42

      vllm:
        gpu_memory_utilization: 0.8
        max_num_batched_tokens: 8192
        enable_chunked_prefill: True
        enable_prefix_caching: True
        dtype: auto
